##################################################
### Configfile for Snakefile-scRNA-seq in YAML ###
##################################################

# Notes:
# You can not use variables in PyYaml so every path must be full
# fill in /.../ with your relevant paths

### Directories ### (Primary locations reused throughout pipeline)
OUTDIR: /.../GitHub/nature_2023_submission_code_2/preprocessing/data #where output data should be stored
SNAKEDIR: /.../GitHub/nature_2023_submission_code_2/preprocessing/src/snakemake #path to the github repository clone
DATADIR: /.../GitHub/nature_2023_submission_code_2/preprocessing/data #where the reference data is

### Reference Genomes ### (Standard and available for download)
reference_unzip: /.../refgenomes/Gencode/v25/GRCh38.primary_assembly.genome.fa
ref_unzip_wdict: /.../refgenomes/Gencode/v25/wdict/GRCh38.primary_assembly.genome.fa
reference_gtf_unzip: /.../refgenomes/Gencode/v25/gencode.v25.primary_assembly.annotation.gtf
readlength: 100

### Reference RPE-1 Data ### (Provided in Repo)
ref_het_SNPs: /.../GitHub/nature_2023_submission_code_2/preprocessing/data/RPE1_refs/RPE-1.hets.chr1-X.BA.SNPs_only.recode.vcf.gz

### Samples Files ### (Names of sequencing files used as 'wildcards' in snakemake)
samplesdir: /.../GitHub/nature_2023_submission_code_2/preprocessing/data/samples
a_samples: /.../GitHub/nature_2023_submission_code_2/preprocessing/data/samples/SIS1025a_samples.txt
b_samples: /.../GitHub/nature_2023_submission_code_2/preprocessing/data/samples/SIS1025b_samples.txt
c_samples: /.../GitHub/nature_2023_submission_code_2/preprocessing/data/samples/SIS1025c_samples.txt
d_samples: /.../GitHub/nature_2023_submission_code_2/preprocessing/data/samples/SIS1025d_samples.txt
e_samples: /.../GitHub/nature_2023_submission_code_2/preprocessing/data/samples/SIS1025e_samples.txt
f1_samples: /.../GitHub/nature_2023_submission_code_2/preprocessing/data/samples/SIS1025f_L1_samples.txt
f2_samples: /.../GitHub/nature_2023_submission_code_2/preprocessing/data/samples/SIS1025f_L2_samples.txt
g1_samples: /.../GitHub/nature_2023_submission_code_2/preprocessing/data/samples/SIS1025g_L1_samples.txt
g2_samples: /.../GitHub/nature_2023_submission_code_2/preprocessing/data/samples/SIS1025g_L2_samples.txt
misc_samples: /.../GitHub/nature_2023_submission_code_2/preprocessing/data/samples/misc_early_samples.txt
targ_samples: /.../GitHub/nature_2023_submission_code_2/preprocessing/data/samples/targeted_MN_samples.txt

### Specific Software Versions ### (Point to your own installations)
GATK_path: /.../GATK/current/GenomeAnalysisTK.jar
Picard_path: /.../Stam_Etai_Packages/picard/current/bin/picard.jar

### Picard Options ###
max_records: 500000 # for configuring picard "max_records_in_ram", determines memory usage

### Temporary File Directory ###
tmp_dir: 'tmp' # location for temporary files generated by gatk and other tools (will overflow /tmp/)
# NOTE: For cluster usage, instead make a folder in high-performance /cluster/ storage

### Thread, CPU, and Core Settings ###
MAX_THREADS: 16
DEFAULT_THREADS: 4

### GATK Options ### 
PICARD_OPTIONS: f'--TMP_DIR 'tmp' --MAX_RECORDS_IN_RAM 16 --USE_JDK_DEFLATER --USE_JDK_INFLATER --COMPRESSION_LEVEL 5'
GATK_FILTERS: ("-RF MappingQualityReadFilter --minimum-mapping-quality 30 -RF OverclippedReadFilter --filter-too-short 50")
